(in-package #:siobud)

(defparameter *default-styles* `("siobud.css"))
(defparameter *default-scripts* `())

(defmacro with-templated-page ((&key title styles scripts) &body content)
  `(cl-who:with-html-output-to-string (*standard-output* nil :prologue t)
     (:head (:title (cl-who:str ,title))
            ,(loop for script in (append *default-scripts* scripts)
                   :collecting `(:script :type "text/javascript" :src ,(concatenate 'string "/js/" script)))
            ,(loop for style in (append *default-styles* styles)
                   :collecting `(:link :rel "stylesheet"  :type "text/css" :href ,(concatenate 'string "/css/" style))))
     (:body (:nav (:ul (:li ((:a :href "/") "Home"))
                (:li (:a "Interests")
                     (:ul  (:li ((:a :href "/interests/music") "Music"))
                           (:li ((:a :href "/interests/computing") "Computing"))))
                            (:li ((:a :href "/blog") "Blog"))
                (:li (:a "Résumé")
                     (:ul (:li ((:a :href "/resume/")           "HTML"))
                          (:li ((:a :href "/resume/resume.pdf") "PDF")))))))
            ((:div :id "frame")
                ((:div :id "about_me")  ((:span :id "name") "Sean DuBois")
                     (:p "Programmer")
                     (:p "Audiophile")
                     ((:img :src "/img/gravatar.jpg" :id "gravatar"))
                     (:br)
                     (:p ((:a :href "http://www.github.com/sean-der") "GitHub"))
                     (:p ((:a :href "http://www.discogs.com/collection?user=Sean-Der") "Discogs"))
                     (:p ((:a :href "mailto:sean@siobud.com") "Email"))
                     (:p ((:a :href "http://twocitygal.blogspot.com/") "Two Cities")))
                ((:div :id "content") ,(first content)))))
