(define-page "/interests/music"
    (lambda ()
    (set-page-title! "(sioBuD.com (Interests (Music)))")
      (template
        `(
          (div (@ (class "article")) (h1 "Music")
            (br)
            (br)
            (h2 "There is more to music than just sound")
            (p "If there is any sentence to sum up my thoughts on music this would be it. It doesn't matter if I am listening to vinyl with a really close friend, trying to convince someone that noise music is relaxing or talking about music with a complete stranger. This is what I see as the beauty of music, the completely subjectivity of it. I love the irrational discussions I can have about it, it doesn't matter what band or genre I bet you someone is willing to defend its merit tooth and nail. This is why my undying obsession with music was born.")
            (img (@ (class "right-image")(src "/img/interests/music/turntable.jpg")))
            (p "My love for music began at a very young age. My parents had a large collection of music and I was introduced to Brian Eno, John Coltrane and Pink Floyd early on. I also am part of the lucky few that were on the internet during the heyday of Napster, XDCC and Soulseek. I was introduced to lots of music by chatting with other people and grabbed tons of music that I would have never heard of on my own. I am not going to try and justify downloading the music, but it did cause me to spend lots of money on vinyl ten years later.")
            (p "I recently started collecting Vinyl also. Its a rewarding, but expensive hobby. You can check out my collection on my " (a (@(href "http://www.discogs.com/collection?user=Sean-Der"))"Discogs") ". I have yet to find a new favorite record store after I moved, but am still looking. I try to avoid ordering vinyl online, while it does give you instant gratification nothing can compare to that feel when you find your grail in a crate of old records")
            (h2 "My setup now") 
            (a (@ (href "javascript:void(0);")) (img (@ (alt "audio-setup") (class "centered-image") (src "/img/interests/music/audio-setup.jpg"))))
            (h3 "Turntable") 
            (p "Right now I am currently using a AT-LP60 as a starter turntable, and it works well for my needs. I still have the factory stylus and belt on it, and don't plan on updating either soon. Its only flaw is the lack of a balance on the tonearm. I recently came came by a Marantz 1060 that has a dull stylus, it may have some other issues but I have yet to throw a scratched up LP on it. I may put some money into restoring this, or watch Craigslist to pick up a nicer turntable entirely")
            (h3 "Receiver")
            (p "I have a Technics SA-310, it sounds great. It does run a bit hot though. I have no intention of replacing it, but if I see something nice come up on craiglist I will grab it")
            (h3 "Speakers")
            (p "However, The prize of my collection is a pair of Energy 5.1e speakers. They sound absolutely amazing, the bass on them sounds rich but not forced. The tweaker on the right side is a bit damaged, but was repaired by the previous owner.")
            (br)
            (p "At this time my knowledge of audio equipment is lacking, but I hope to improve it in the near future. This hobby has been put to the wayside a bit because of a move and a new job, but I hope to pick it up in full swing soon.")
            (h2 "Interesting Music")
            ))))
    headers: (include-javascript "/js/centered-image.js"))
